### ISSUE TITLE
Close Infowindow on MapView Clicked

### ISSUE THREAD

**Issue by SaeedBahari** [utsmannn/osm-android-compose#10]
add close infoWindow when user click on any place on map. this feature is available on base osmdroid library.

ref: https://github.com/osmdroid/osmdroid/wiki/Markers,-Lines-and-Polygons-(Kotlin) (Section OnOpen function)

**Comment by utsmannn** [comment]
For current version not supported configure it on marker. Please use `onMapClick` parameter on `OpenStreetMap` composable for setting up InfoWindow visibility. It is posible caused InfoWindow is composable function.
